name: build

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '40 6 * * 5'

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start container
        run: docker run -d --rm --name hello-world crccheck/hello-world
      - name: Wait for container
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: hello-world
          wait-time: 50
          require-status: running
          require-healthy: true
